### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by rboeije1** [balk77/node-red-buttonplus-menu#4]
I did not yet receive my B+, but tried to import the flows just to see how to implement.
But I got a couple of errors, depite the dependency-list. A few I could find in the palette, but not all.
Does it depend on certain HA-sprecfic add-ons?
Like server-state-changed, api-call-service and server.
I am using nodered, w/o HA.

**Comment by balk77** [comment]
Removed some node types, the only external node type is https://flows.nodered.org/node/node-red-contrib-home-assistant-websocket
